// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIC52BRlk3hXCacZSmRy4uGuO1pjExnjg',
    appId: '1:722482686399:web:64d1d4966981531581990a',
    messagingSenderId: '722482686399',
    projectId: 'ayurvedic-app-95f44',
    authDomain: 'ayurvedic-app-95f44.firebaseapp.com',
    storageBucket: 'ayurvedic-app-95f44.firebasestorage.app',
    measurementId: 'G-HQBNYNVKHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCUAKtGdpjXeDM-JQD2aYandpVbzdunhk',
    appId: '1:722482686399:android:724095761ac1c43181990a',
    messagingSenderId: '722482686399',
    projectId: 'ayurvedic-app-95f44',
    storageBucket: 'ayurvedic-app-95f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqm4-I2jqJ-u5shn_a0MNuPBOllDABT9c',
    appId: '1:722482686399:ios:a48aacf4a8d3551a81990a',
    messagingSenderId: '722482686399',
    projectId: 'ayurvedic-app-95f44',
    storageBucket: 'ayurvedic-app-95f44.firebasestorage.app',
    iosBundleId: 'com.example.ayurvedicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqm4-I2jqJ-u5shn_a0MNuPBOllDABT9c',
    appId: '1:722482686399:ios:a48aacf4a8d3551a81990a',
    messagingSenderId: '722482686399',
    projectId: 'ayurvedic-app-95f44',
    storageBucket: 'ayurvedic-app-95f44.firebasestorage.app',
    iosBundleId: 'com.example.ayurvedicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIC52BRlk3hXCacZSmRy4uGuO1pjExnjg',
    appId: '1:722482686399:web:25584687cec6093c81990a',
    messagingSenderId: '722482686399',
    projectId: 'ayurvedic-app-95f44',
    authDomain: 'ayurvedic-app-95f44.firebaseapp.com',
    storageBucket: 'ayurvedic-app-95f44.firebasestorage.app',
    measurementId: 'G-GFHM7BSWNS',
  );
}
